version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: defaultdb
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network

  orderservice:
    build:
      context: .
      dockerfile: ./OrderService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:8080"
    networks:
      - my_network
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  productservice:
    build:
      context: .
      dockerfile: ./ProductService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080"
    networks:
      - my_network
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  userservice:
    build:
      context: .
      dockerfile: ./UserService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"
    networks:
      - my_network
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  eventstoreservice:
    build:
      context: .
      dockerfile: ./EventStoreService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:8080"
    networks:
      - my_network
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_started

networks:
  my_network:
    driver: bridge
